#!/usr/bin/env python3
"""Generate the DSH prompt companion from the canonical runtime policy."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.runtime_prompt import RUNTIME_PROMPT, RUNTIME_PROMPT_REVISION

OUTPUT = ROOT / "dsh" / "runtime-prompt-companion.js"
SECTION_NAME = "mcp:taobao:runtime-policy"


def render() -> str:
    prompt = json.dumps(RUNTIME_PROMPT, ensure_ascii=False)
    revision = json.dumps(RUNTIME_PROMPT_REVISION)
    section_name = json.dumps(SECTION_NAME)
    return f"""// Generated by dsh/build_runtime_prompt_companion.py. Do not edit.
export const name = 'taobao-mcp-runtime-prompt-companion';
export const inject = ['systemPrompt'];
export const runtimePromptRevision = {revision};

export function apply(ctx) {{
  ctx.systemPrompt.section({{
    name: {section_name},
    order: 45,
    text: {prompt},
  }});
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"Runtime prompt companion is stale: {OUTPUT}")
        print(f"Runtime prompt companion is current: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
